Repository Avanade/emtech-distributed-data, pull requests merged in 2021-06, with the labels that each got.

#82 62 set up confidential ledger
  .github/workflows/oss-compliance.yml
  confidential-server/.env.template
  confidential-server/ReadMe.md
  confidential-server/confidential-setup.http
  confidential-server/confidential-setup.py
  python-tools/requirements.txt
Labels: enhancement

#84 updated oss-compliance file
  .github/workflows/oss-compliance.yml
Labels: bug

#85 Merging confidential-ledger updates into main
  .github/workflows/oss-compliance.yml
  confidential-server/.env.template
  confidential-server/ReadMe.md
  confidential-server/confidential-setup.http
  confidential-server/confidential-setup.py
  python-tools/requirements.txt
Labels: enhancement

#87 refactor(confidential-ledger): reorganized folder structure and updated docs
  .github/workflows/build-confidential-ledger.yml
  .github/workflows/oss-compliance.yml
  confidential-ledger-demo/client/Dockerfile
  confidential-ledger-demo/client/components/Car.tsx
  confidential-ledger-demo/client/components/CarGrid.tsx
  confidential-ledger-demo/client/components/Layout.tsx
  confidential-ledger-demo/client/components/Motorway.tsx
  confidential-ledger-demo/client/components/Panel.tsx
  confidential-ledger-demo/client/components/SlideOver.tsx
  confidential-ledger-demo/client/lib/CarSimulation.ts
  confidential-ledger-demo/client/next-env.d.ts
  confidential-ledger-demo/client/package-lock.json
  confidential-ledger-demo/client/package.json
  confidential-ledger-demo/client/pages/_app.js
  confidential-ledger-demo/client/pages/index.js
  confidential-ledger-demo/client/pages/simulate.js
  confidential-ledger-demo/client/postcss.config.js
  confidential-ledger-demo/client/public/favicon.ico
  confidential-ledger-demo/client/public/oltiva-logo.png
  confidential-ledger-demo/client/tailwind.config.js
  confidential-ledger-demo/client/tsconfig.json
  confidential-ledger-demo/server/.env.template
  confidential-ledger-demo/server/confidential-setup.http
  confidential-ledger-demo/server/confidential-setup.py
  confidential-ledger-demo/server/requirements.txt
  docs/confidential-ledger-setup.md
  docs/start-here.md
  sql-ledger-demo/.dockerignore
  sql-ledger-demo/sql/Setup.sql
  sql-ledger-demo/sql/procedures.sql
Labels: enhancement

#101 feat(confidential-ledger): workign server, read data from guid
  confidential-ledger-demo/server/app.py
  confidential-ledger-demo/server/confidential-ledger.py
  confidential-ledger-demo/server/confidentialledger.py
  confidential-ledger-demo/server/requirements.txt
  pyproject.toml
Labels: enhancement

#103 98 update credential method for server
  confidential-ledger-demo/server/.env.template
  confidential-ledger-demo/server/app.py
  confidential-ledger-demo/server/confidentialledger.py
  confidential-ledger-demo/server/sampledata.json
  confidential-ledger-demo/server/templates/layout/base.html
Labels: enhancement, security findings

#105 104-Dockerize-confidential-ledger-setup
  confidential-ledger-demo/docker-compose.yml
  confidential-ledger-demo/server/Dockerfile
  confidential-ledger-demo/server/app.py
Labels: security findings

#106 31 document setup for backend
  confidential-ledger-demo/server/confidential-setup.py
  confidential-ledger-demo/server/confidential-usage.http
  confidential-ledger-demo/server/confidentialledger.py
  docs/confidential-ledger-setup.md
  docs/confidential-ledger.md
  docs/sampledata.json
Labels: documentation

#109 108 pin the requirements for requirementstxt
  confidential-ledger-demo/server/.env.template
  confidential-ledger-demo/server/confidential-setup.py
  confidential-ledger-demo/server/confidentialledger.py
  confidential-ledger-demo/server/requirements-dev.txt
  confidential-ledger-demo/server/requirements.txt
Labels: security findings

#115 fix(confidential-ledger): reads .env into docker container for server
  confidential-ledger-demo/docker-compose.yml
  confidential-ledger-demo/server/.dockerignore
  confidential-ledger-demo/server/date_funcs.py
Labels: bug

#116 feat(confidential-ledger): update append to handle a passed guid as /…
  confidential-ledger-demo/server/app.py
  confidential-ledger-demo/server/confidentialledger.py
Labels: bug, enhancement

#118 107 move python setup
  confidential-ledger-demo/server/confidential-setup.py
  docs/confidential-ledger-setup-python.md
Labels: documentation

#125 119-Integrate-ledger-append-function-into-simulation
  confidential-ledger-demo/client/components/CarVisualizations.tsx
  confidential-ledger-demo/client/components/MotorwayGrid.tsx
  confidential-ledger-demo/client/lib/CarSimulation.ts
  confidential-ledger-demo/client/lib/TestCarSimulation.ts
  confidential-ledger-demo/client/pages/simulate.tsx
Labels: enhancement

#127 126-Update-github-actions-for-new-docker-setup
  .github/workflows/build-confidential-ledger.yml
  README.md
  confidential-ledger-demo/docker-compose.yml
  docs/confidential-ledger-images/architecture.png
  docs/confidential-ledger-images/use-case.png
  docs/confidential-ledger-setup-python.md
  docs/confidential-ledger-setup.md
  docs/confidential-ledger-usecase.md
  docs/confidential-ledger.md
  docs/sql-ledger.md
  docs/start-here.md
Labels: documentation
